version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: api-2025
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongo_data:
