apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort  # Para exponer la API fuera de Minikube
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: api  # Conecta con los pods de la API
